name: pyradio
summary: Command line internet radio player.
description: |
  Command line internet radio player.
  
  **Authors**

  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or officially maintained by the upstream developers.

base: core24
grade: stable
confinement: strict

website: https://github.com/coderholic/pyradio
contact: https://github.com/snapcrafters/pyradio/issues
issues: https://github.com/snapcrafters/pyradio/issues
source-code: https://github.com//snapcrafters/pyradio
license: MIT
version: '0.9.3.11.31'

platforms:
  amd64:
  arm64:
  armhf:

apps:
  pyradio:
    command: bin/pyradio-wrapper
    plugs:
        - audio-playback
        - network
        - network-bind

parts:
  pyradio:
    plugin: python
    source: https://github.com/coderholic/pyradio.git
    python-requirements:
        - requirements_pipx.txt
    override-build: |
        git apply "$CRAFT_PROJECT_DIR/snap/local/pyradio-mpv-socket.patch"
        grep -F "SNAP_USER_COMMON" pyradio/player.py
        craftctl default
    stage-packages:
        - mpv
        - libblas3

  pyradio-wrapper:
    plugin: dump
    source: snap/local
    organize:
        mpv: bin/mpv
        pyradio-wrapper: bin/pyradio-wrapper
    after:
        - pyradio
